plugins {
    id 'net.neoforged.moddev.legacyforge' version '2.0.137'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

dependencies {
    compileOnly "vazkii.botania:Botania:${minecraft_version}-440.2-FORGE:api"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    modImplementation "net.enderturret:VariableSkins-${minecraft_version}-forge:${variableskins_version}"
}

mixin {
    add sourceSets.main, 'tailslegacy.refmap.json'
    config 'mixins.tailslegacy.json'
}

tasks.named('jar', Jar).configure {
    manifest.attributes([
        'MixinConfigs': 'mixins.tailslegacy.json'
    ])
}

legacyForge {
    version = "${minecraft_version}-${loader_version}"

    mods {
        tails {
            sourceSet sourceSets.main
            sourceSet project(':Tails.Common').sourceSets.main
        }
    }

    parchment {
        minecraftVersion = "${minecraft_version}"
        mappingsVersion = "${mappings_version}"
    }

    runs {
        client {
            client()
            ideName = 'runTailsClientForge1_19_2'
            if (rootProject.findProperty('minecraft_username') != null) {
                programArguments.addAll('--uuid', rootProject.findProperty('minecraft_uuid'), '--username', rootProject.findProperty('minecraft_username'))
            }
        }

        server {
            server()
            ideName = 'runTailsServerForge1_19_2'
        }
    }
}