minecraft_version=1.21.11
loader=1.21.11-neoforge
loader_version=21.11.25-beta

# https://parchmentmc.org/docs/getting-started
# https://ldtteam.jfrog.io/ui/native/parchmentmc-public/org/parchmentmc/data/
mappings_version=2025.12.20

publishing_loader=neoforge
publishing_minecraft_version_range=1.21.11
publishing_java_version=VERSION_21