plugins {
    id 'me.modmuss50.mod-publish-plugin' version '2.2.0' apply false
}

group = 'net.enderturret'

tasks.register('publishMods') {
    def tasks = [
        project(':Tails.Forge.1.7.10').tasks.publishMods,
        project(':Tails.Forge.1.12.2').tasks.publishMods,
        project(':Tails.Forge.1.18.2').tasks.publishMods,
        project(':Tails.Forge.1.19.2').tasks.publishMods,
        project(':Tails.Forge.1.20.1').tasks.publishMods,
        project(':Tails.NeoForge.1.21.1').tasks.publishMods,
        project(':Tails.NeoForge.1.21.11').tasks.publishMods,
        project(':Tails.NeoForge.26.1').tasks.publishMods
    ]

    for (int i = 0; i < tasks.size() - 1; i++) {
        tasks[i + 1].mustRunAfter(tasks[i])
    }

    dependsOn(tasks)
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'eclipse'
    apply plugin: 'idea'
    apply plugin: 'maven-publish'

    java.withSourcesJar()

    group = 'net.enderturret'
    version = "${mod_version}+${loader}"

    base {
        archivesName = 'TailsLegacy'
    }

    repositories {
        maven {
            url = 'https://maven.blamejared.com'
            content {
                includeGroup 'vazkii.botania'
                includeGroup 'vazkii.patchouli'
            }
        }
        maven {
            url = 'https://maven.theillusivec4.top'
            content {
                includeGroup 'top.theillusivec4.curios'
            }
        }
        maven {
            url = 'https://api.modrinth.com/maven'
            content {
                includeGroup 'maven.modrinth'
            }
        }
        mavenLocal {
            content {
                includeGroup 'net.enderturret'
            }
        }
    }

    tasks.named('processResources', ProcessResources).configure {
        doLast {
            fileTree(dir: outputs.files.asPath, include: '**/*.json').each {
                File file -> file.text = groovy.json.JsonOutput.toJson(new groovy.json.JsonSlurper().parse(file))
            }
        }
    }

    tasks.named('jar', Jar).configure {
        manifest {
            attributes([
                'Specification-Title': 'Tails Legacy',
                'Specification-Vendor': 'EnderTurret',
                'Specification-Version': '1',
                'Implementation-Title': 'Tails Legacy',
                'Implementation-Version': "${version}",
                'Implementation-Vendor': 'EnderTurret'
            ])
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
    }

    tasks.withType(AbstractArchiveTask).configureEach {
        preserveFileTimestamps = false
        reproducibleFileOrder = true
    }

    configurations {
        localImplementation
        compileClasspath.extendsFrom localImplementation
        runtimeClasspath.extendsFrom localImplementation
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifactId = "TailsLegacy-${loader}"
                version = "${mod_version}"

                from components.java

                pom {
                    description = 'For all your taily needs.'
                }
            }
        }
    }

    if (it != project(':Tails.Common')) {
        tasks.named('compileJava', JavaCompile).configure {
            source project(':Tails.Common').sourceSets.main.allSource
        }

        tasks.named('sourcesJar', Jar).configure {
            from project(':Tails.Common').sourceSets.main.allJava
        }

        tasks.named('processResources', ProcessResources).configure {
            from project(':Tails.Common').sourceSets.main.resources
        }

        dependencies {
            localImplementation (project(':Tails.Common'))
        }

        apply plugin: 'me.modmuss50.mod-publish-plugin'

        publishMods {
            file = jar.archiveFile
            changelog = providers.fileContents(rootProject.getLayout().projectDirectory.file("changelog.md")).asText
            type = STABLE
            modLoaders.add("${publishing_loader}")
            displayName = "${project.version}"

            dryRun = false

            curseforge {
                accessToken = providers.gradleProperty('CURSEFORGE_API_KEY')
                projectId = '1632857'
                changelogType = 'markdown'

                additionalFiles.from(sourcesJar.archiveFile)

                minecraftVersionList("${publishing_minecraft_version_range}")
                javaVersions.add(JavaVersion.valueOf("${publishing_java_version}"))

                client = true
                server = true

                if (project.hasProperty("publishing_mixin_dep_cf")) {
                    requires("${publishing_mixin_dep_cf}")
                }
            }

            modrinth {
                accessToken = providers.gradleProperty('MODRINTH_API_KEY')
                projectId = 'MUD8QUkv'

                additionalFile(sourcesJar) {
                    type = SOURCES_JAR
                }

                minecraftVersionList("${publishing_minecraft_version_range}")

                environment = CLIENT_OR_SERVER_PREFERS_BOTH

                if (project.hasProperty("publishing_mixin_dep_mr")) {
                    requires("${publishing_mixin_dep_mr}")
                }
            }
        }
    }
}