plugins {
    id 'eclipse'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '1.0.21'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)
java.withSourcesJar()

repositories {
    //maven { url 'https://maven.blamejared.com' }
    //maven { url 'https://maven.theillusivec4.top' }
}

group = 'uk.kihira'
version = '3.2.5+1.21.1'

base {
    archivesName = 'Tails'
}

dependencies {
    //compileOnly 'vazkii.botania:Botania:1.20.1-446-FORGE:api'
    //runtimeOnly 'vazkii.botania:Botania:1.20.1-446-FORGE'
    //runtimeOnly 'vazkii.patchouli:Patchouli:1.21-87-NEOFORGE'
    //runtimeOnly 'top.theillusivec4.curios:curios-forge:5.2.0-beta.3+1.20.1'
}

neoForge {
    version = '21.1.72'

    mods {
        tails {
            sourceSet sourceSets.main
        }
    }

    parchment {
        // https://parchmentmc.org/docs/getting-started
        // https://ldtteam.jfrog.io/ui/native/parchmentmc-public/org/parchmentmc/data/
        minecraftVersion = '1.21'
        mappingsVersion = '2024.07.28'
    }

    runs {
        client {
            client()
            ideName = 'runTailsClient'
        }

        server {
            server()
            ideName = 'runTailsServer'
        }
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
            'Specification-Title': 'Tails',
            'Specification-Vendor': 'Kihira',
            'Specification-Version': '1',
            'Implementation-Title': project.name,
            'Implementation-Version': "${version}",
            'Implementation-Vendor': 'EnderTurret'
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

tasks.withType(AbstractArchiveTask).configureEach {
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            pom {
                name = 'Tails'
                description = 'For all your taily needs.'
            }
        }
    }
}