modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/kihira/Tails/issues"
[[mods]]
    modId="tails"
    displayName="Tails"
	displayURL="https://github.com/kihira/Tails"
    description='''
        For all your taily needs
    '''
    version="${version}"
    authors="Kihira"

[[dependencies.tails]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tails]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"