minecraft_version=1.20.1
loader=1.20.1-forge
loader_version=47.4.13

# https://parchmentmc.org/docs/getting-started
# https://ldtteam.jfrog.io/ui/native/parchmentmc-public/org/parchmentmc/data/
mappings_version=2023.09.03

publishing_loader=forge
publishing_minecraft_version_range=1.20, 1.20.1
publishing_java_version=VERSION_17