plugins {
    id 'net.neoforged.moddev' version '2.0.137'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    version = "${loader_version}"

    mods {
        tails {
            sourceSet sourceSets.main
            sourceSet project(':Tails.Common').sourceSets.main
        }
    }

    runs {
        client {
            client()
            ideName = 'runTailsClientNeoForge26_1'
            if (rootProject.findProperty('minecraft_username') != null) {
                programArguments.addAll('--uuid', rootProject.findProperty('minecraft_uuid'), '--username', rootProject.findProperty('minecraft_username'))
            }
        }

        server {
            server()
            ideName = 'runTailsServerNeoForge26_1'
        }
    }
}